apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:                                                                                              
    - port: 8888
      targetPort: 8888
      nodePort: 30007